import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) => ({
  formContainer: {
    minHeight: "100vh",
    background: "radial-gradient(ellipse 70% 55% at 75% -10%, rgba(0,212,216,0.2) 0%, transparent 60%), radial-gradient(ellipse 50% 45% at -5% 80%, rgba(168,255,120,0.07) 0%, transparent 55%), #0c0e14",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "40px 20px",
    fontFamily: "'DM Sans', sans-serif",
  },
  authWrapper: {
    width: "100%",
    maxWidth: "1080px",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: "32px",
    alignItems: "stretch",
  },
  heroSection: {
    background: "rgba(24,27,38,0.7)",
    backdropFilter: "blur(20px)",
    borderRadius: "24px",
    padding: "40px",
    border: "1px solid rgba(255,255,255,0.07)",
    boxShadow: "0 40px 80px rgba(0,0,0,0.5)",
    color: "#f0f2ff",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    position: "relative",
    overflow: "hidden",
    "&::before": {
      content: '""',
      position: "absolute",
      top: 0, left: "20%", right: "20%",
      height: "1px",
      background: "linear-gradient(90deg, transparent, #00d4d8, transparent)",
    },
  },
  heroBadge: {
    alignSelf: "flex-start",
    fontSize: "0.7rem",
    letterSpacing: "0.2em",
    textTransform: "uppercase",
    background: "linear-gradient(135deg, #00d4d8, #00b8bc)",
    borderRadius: "999px",
    padding: "6px 16px",
    fontWeight: 700,
    color: "#071014",
  },
  heroTitle: {
    fontFamily: "'Syne', sans-serif !important",
    fontSize: "2rem !important",
    fontWeight: "800 !important",
    lineHeight: "1.15 !important",
    letterSpacing: "-0.025em",
    color: "#f0f2ff !important",
  },
  heroSubtitle: {
    color: "rgba(240,242,255,0.55) !important",
    fontSize: "0.95rem !important",
    lineHeight: "1.65 !important",
  },
  heroList: {
    listStyle: "none",
    margin: 0, padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  heroItem: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "0.9rem",
    color: "rgba(240,242,255,0.75)",
  },
  heroCircle: {
    width: "6px", height: "6px",
    borderRadius: "50%",
    background: "#00d4d8",
    boxShadow: "0 0 8px rgba(0,212,216,0.6)",
    flexShrink: 0,
  },
  secondaryButton: {
    marginTop: "24px !important",
    alignSelf: "flex-start",
    borderRadius: "12px !important",
    padding: "12px 28px !important",
    fontWeight: "600 !important",
    background: "rgba(0,212,216,0.12) !important",
    color: "#00d4d8 !important",
    border: "1px solid rgba(0,212,216,0.25) !important",
    fontSize: "0.875rem !important",
    fontFamily: "'DM Sans', sans-serif !important",
    transition: "all 0.2s !important",
    "&:hover": {
      background: "rgba(0,212,216,0.2) !important",
      transform: "translateY(-1px)",
    },
  },
  formSection: {
    display: "flex",
    alignItems: "stretch",
  },
  formCard: {
    flex: 1,
    background: "rgba(24,27,38,0.85)",
    backdropFilter: "blur(20px)",
    borderRadius: "24px",
    padding: "40px",
    border: "1px solid rgba(255,255,255,0.07)",
    boxShadow: "0 40px 80px rgba(0,0,0,0.5)",
    display: "flex",
    flexDirection: "column",
    position: "relative",
    overflow: "hidden",
    "&::before": {
      content: '""',
      position: "absolute",
      top: 0, left: "20%", right: "20%",
      height: "1px",
      background: "linear-gradient(90deg, transparent, rgba(168,255,120,0.5), transparent)",
    },
  },
  formHeader: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "8px",
    marginBottom: "28px",
  },
  avatar: {
    background: "linear-gradient(135deg, #00d4d8, #00b8bc) !important",
    width: "48px !important",
    height: "48px !important",
    marginBottom: "8px !important",
  },
  heading: {
    fontFamily: "'Syne', sans-serif !important",
    fontSize: "1.6rem !important",
    fontWeight: "800 !important",
    color: "#f0f2ff !important",
    letterSpacing: "-0.025em",
  },
  formDescription: {
    fontSize: "0.875rem !important",
    color: "rgba(240,242,255,0.5) !important",
    lineHeight: "1.6 !important",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    width: "100%",
  },
  textField: {
    "& .MuiOutlinedInput-root": {
      borderRadius: "12px",
      background: "rgba(255,255,255,0.04)",
      fontFamily: "'DM Sans', sans-serif",
      "& fieldset": { borderColor: "rgba(255,255,255,0.1)" },
      "&:hover fieldset": { borderColor: "rgba(255,255,255,0.2)" },
      "&.Mui-focused fieldset": { borderColor: "#00d4d8" },
    },
    "& .MuiInputLabel-root": {
      color: "rgba(240,242,255,0.45)",
      fontFamily: "'DM Sans', sans-serif",
      fontSize: "0.875rem",
      "&.Mui-focused": { color: "#00d4d8" },
    },
    "& .MuiOutlinedInput-input": {
      color: "#f0f2ff",
      fontSize: "0.9rem",
      padding: "14px 16px",
    },
    "& .MuiFormHelperText-root": {
      color: "#ff8080",
      fontSize: "0.75rem",
    },
  },
  emailInput: {},
  passwordInput: {},
  rememberMeContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: "-4px",
  },
  forgotPasswordLink: {
    color: "#00d4d8 !important",
    fontSize: "0.82rem",
    textDecoration: "none",
    fontWeight: 500,
    "&:hover": { textDecoration: "underline" },
  },
  loginButton: {
    borderRadius: "12px !important",
    padding: "14px !important",
    background: "linear-gradient(135deg, #00d4d8, #00b8bc) !important",
    color: "#071014 !important",
    fontWeight: "700 !important",
    fontSize: "0.95rem !important",
    fontFamily: "'DM Sans', sans-serif !important",
    letterSpacing: "0.01em",
    boxShadow: "0 8px 24px rgba(0,212,216,0.35) !important",
    transition: "all 0.2s !important",
    marginTop: "4px !important",
    "&:hover": {
      transform: "translateY(-1px)",
      boxShadow: "0 14px 32px rgba(0,212,216,0.45) !important",
    },
    "&:disabled": {
      opacity: "0.4 !important",
      transform: "none !important",
    },
  },
  showPasswordButton: {
    minWidth: "unset !important",
    border: "none !important",
    background: "transparent !important",
    color: "rgba(240,242,255,0.4) !important",
    padding: "4px !important",
    "&:hover": { background: "transparent !important", color: "#00d4d8 !important" },
  },
  createAccount: {
    color: "#00d4d8 !important",
    fontWeight: "600",
    textDecoration: "none",
    marginLeft: "6px",
    "&:hover": { textDecoration: "underline" },
  },
  // Signup extras
  uploadArea: {
    border: "1px dashed rgba(0,212,216,0.3)",
    borderRadius: "12px",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "10px",
    cursor: "pointer",
    transition: "all 0.2s",
    background: "rgba(0,212,216,0.04)",
    "&:hover": {
      borderColor: "rgba(0,212,216,0.5)",
      background: "rgba(0,212,216,0.08)",
    },
  },
  uploadLabel: {
    fontSize: "0.85rem !important",
    color: "rgba(240,242,255,0.5) !important",
    cursor: "pointer",
    fontFamily: "'DM Sans', sans-serif",
  },
  uploadPreview: {
    width: "64px", height: "64px",
    borderRadius: "50%",
    objectFit: "cover",
    border: "2px solid rgba(0,212,216,0.4)",
  },
}));

export default useStyles;
